import type { MartialArtDef, MartialCategory } from './MartialTypes';

const DEFAULT_PROGRESSION = { maxLevel: 10, expCurve: 'linear' as const, hitExp: 2, missExp: 1 };

export const MARTIAL_ARTS: Record<string, MartialArtDef> = {
  taizu_changquan: {
    id: 'taizu_changquan',
    name: '太祖长拳',
    category: 'fist',
    tier: 1,
    role: 'attack',
    description: '基础拳法，朴素直接，练到深处拳劲沉稳。',
    flavor: '拳路方正，以稳破虚。',
    unlock: { manualIds: ['manual_taizu_changquan'] },
    progression: DEFAULT_PROGRESSION,
    combat: { mpCost: 6, basePower: 78, powerGrowth: 5, hitRate: 92, target: 'enemy' },
    tactical: { range: 1, aoeSize: 1, shape: 'single' },
    horizontal: { presentation: 'ranged', spineAction: 'skill1', hitDelayMs: 260 },
  },
  taiji_quan: {
    id: 'taiji_quan',
    name: '太极拳',
    category: 'fist',
    tier: 3,
    role: 'attack',
    description: '高阶拳法，以柔克刚，圆转如意。',
    flavor: '圆劲一转，借力反推。',
    unlock: { manualIds: ['manual_taiji_quan'] },
    progression: DEFAULT_PROGRESSION,
    combat: { mpCost: 18, basePower: 105, powerGrowth: 7, hitRate: 95, target: 'enemy' },
    tactical: { range: 1, aoeSize: 3, shape: 'cross' },
    horizontal: { presentation: 'melee', spineAction: 'skill4', hitDelayMs: 360 },
  },
  tiancan_leg: {
    id: 'tiancan_leg',
    name: '天残脚',
    category: 'leg',
    tier: 4,
    role: 'attack',
    description: '高爆发腿法，下压如山，命中时气浪沉重。',
    flavor: '一脚落下，天地同残。',
    unlock: { manualIds: ['manual_tiancan_leg'] },
    progression: { ...DEFAULT_PROGRESSION, expCurve: 'rare' },
    combat: { mpCost: 30, basePower: 145, powerGrowth: 9, hitRate: 84, target: 'enemy' },
    tactical: { range: 2, aoeSize: 3, shape: 'diamond' },
    horizontal: { presentation: 'melee', spineAction: 'skill4', hitDelayMs: 430 },
  },
  shadowless_leg: {
    id: 'shadowless_leg',
    name: '无影脚',
    category: 'leg',
    tier: 2,
    role: 'attack',
    description: '迅疾腿法，以残影连击压住对手。',
    flavor: '脚未至，影先到。',
    unlock: { manualIds: ['manual_shadowless_leg'] },
    progression: DEFAULT_PROGRESSION,
    combat: { mpCost: 14, basePower: 92, powerGrowth: 6, hitRate: 96, target: 'enemy' },
    tactical: { range: 2, aoeSize: 1, shape: 'single' },
    horizontal: { presentation: 'melee', spineAction: 'skill4', hitDelayMs: 220 },
  },
  songfeng_sword: {
    id: 'songfeng_sword',
    name: '松风剑法',
    category: 'sword',
    tier: 1,
    role: 'attack',
    description: '入门剑法，剑势轻快，如松间清风。',
    flavor: '剑风清亮，去势不绝。',
    unlock: { manualIds: ['manual_songfeng_sword'] },
    progression: DEFAULT_PROGRESSION,
    combat: { mpCost: 8, basePower: 82, powerGrowth: 5, hitRate: 94, target: 'enemy' },
    tactical: { range: 2, aoeSize: 1, shape: 'line' },
    horizontal: { presentation: 'melee', spineAction: 'attack', hitDelayMs: 280 },
  },
  dugu_jiujian: {
    id: 'dugu_jiujian',
    name: '独孤九剑',
    category: 'sword',
    tier: 4,
    role: 'attack',
    description: '宗师剑法，重在破招，剑意从多向同时切入。',
    flavor: '无招胜有招，一剑破万法。',
    unlock: { manualIds: ['manual_dugu_jiujian'] },
    progression: { ...DEFAULT_PROGRESSION, expCurve: 'rare' },
    combat: { mpCost: 34, basePower: 155, powerGrowth: 9, hitRate: 90, target: 'enemy' },
    tactical: { range: 2, aoeSize: 3, shape: 'line' },
    horizontal: { presentation: 'melee', spineAction: 'skill4', hitDelayMs: 430 },
  },
  gale_blade: {
    id: 'gale_blade',
    name: '狂风刀法',
    category: 'blade',
    tier: 2,
    role: 'attack',
    description: '快刀武功，多段刀风连续压制。',
    flavor: '刀势如狂风，连绵不绝。',
    unlock: { manualIds: ['manual_gale_blade'] },
    progression: DEFAULT_PROGRESSION,
    combat: { mpCost: 16, basePower: 104, powerGrowth: 6, hitRate: 88, target: 'enemy' },
    tactical: { range: 1, aoeSize: 3, shape: 'cross' },
    horizontal: { presentation: 'melee', spineAction: 'attack', hitDelayMs: 320 },
  },
  xueyin_blade: {
    id: 'xueyin_blade',
    name: '雪饮狂刀',
    category: 'blade',
    tier: 4,
    role: 'attack',
    description: '高阶刀法，寒霜刀气重斩而下。',
    flavor: '寒意入骨，刀落如雪崩。',
    unlock: { manualIds: ['manual_xueyin_blade'] },
    progression: { ...DEFAULT_PROGRESSION, expCurve: 'rare' },
    combat: { mpCost: 32, basePower: 160, powerGrowth: 10, hitRate: 82, target: 'enemy' },
    tactical: { range: 1, aoeSize: 3, shape: 'cross' },
    horizontal: { presentation: 'melee', spineAction: 'skill4', hitDelayMs: 460 },
  },
  tuna_intro: {
    id: 'tuna_intro',
    name: '吐纳入门',
    category: 'inner',
    tier: 1,
    role: 'inner',
    description: '基础内功，调息聚气，打稳内力根基。',
    flavor: '一呼一吸，内息自生。',
    unlock: { manualIds: ['manual_tuna_intro'] },
    progression: DEFAULT_PROGRESSION,
    combat: { mpCost: 10, basePower: 72, powerGrowth: 4, hitRate: 96, target: 'enemy' },
    tactical: { range: 2, aoeSize: 1, shape: 'single' },
    horizontal: { presentation: 'ranged', spineAction: 'skill4', hitDelayMs: 320 },
  },
  golden_bell: {
    id: 'golden_bell',
    name: '金钟罩',
    category: 'inner',
    tier: 2,
    role: 'defense',
    description: '护体内功，金钟虚影护住周身。',
    flavor: '钟鸣一响，诸邪难侵。',
    unlock: { manualIds: ['manual_golden_bell'] },
    progression: DEFAULT_PROGRESSION,
    combat: { mpCost: 18, basePower: 86, powerGrowth: 5, hitRate: 92, target: 'enemy' },
    tactical: { range: 1, aoeSize: 3, shape: 'diamond' },
    horizontal: { presentation: 'self', spineAction: 'defense', hitDelayMs: 360 },
  },
  taishan_pressure: {
    id: 'taishan_pressure',
    name: '泰山压顶',
    category: 'ultimate',
    tier: 5,
    role: 'ultimate',
    description: '绝学，山岳虚影自上压落，形成大范围压制。',
    flavor: '泰山当前，万物俯首。',
    unlock: { manualIds: ['manual_taishan_pressure'] },
    progression: { ...DEFAULT_PROGRESSION, expCurve: 'ultimate' },
    combat: { mpCost: 48, basePower: 188, powerGrowth: 12, hitRate: 86, target: 'enemy' },
    tactical: { range: 3, aoeSize: 3, shape: 'diamond' },
    horizontal: { presentation: 'ranged', spineAction: 'skill4', hitDelayMs: 540 },
  },
};

export const MARTIAL_CATEGORY_LABELS: Record<MartialCategory, string> = {
  fist: '拳法',
  leg: '腿法',
  sword: '剑法',
  blade: '刀法',
  inner: '内功',
  ultimate: '绝学',
};

export function getMartialArtDef(martialId: string): MartialArtDef | undefined {
  return MARTIAL_ARTS[martialId];
}

export function getAllMartialArtDefs(): MartialArtDef[] {
  return Object.values(MARTIAL_ARTS);
}
